### ISSUE TITLE
when i run trains_model.py i am getting this error....i am beginner,if any help would be greatfull.

### ISSUE THREAD

**Issue by veenah** [carlini/nn_robust_attacks#24]
/usr/bin/python3.5 /home/veena/Desktop/nn_robust_attacks-master/train_models.py
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
(45000, 32, 32, 3)
WARNING:tensorflow:From /home/veena/Desktop/nn_robust_attacks-master/train_models.py:54: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Traceback (most recent call last):
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 521, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 521, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got /dense_3_target

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/veena/Desktop/nn_robust_attacks-master/train_models.py", line 109, in <module>
    train(CIFAR(), "models/cifar", [64, 64, 128, 128, 256, 256], num_epochs=50)
  File "/home/veena/Desktop/nn_robust_attacks-master/train_models.py", line 60, in train
    metrics=['accuracy'])
  File "/home/veena/.local/lib/python3.5/site-packages/keras/engine/training.py", line 333, in compile
    sample_weight, mask)
  File "/home/veena/.local/lib/python3.5/site-packages/keras/engine/training_utils.py", line 403, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/veena/Desktop/nn_robust_attacks-master/train_models.py", line 54, in fn
    logits=predicted/train_temp)
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1965, in softmax_cross_entropy_with_logits
    labels = array_ops.stop_gradient(labels, name="labels_stop_gradient")
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8030, in stop_gradient
    "StopGradient", input=input, name=name)
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/veena/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 525, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'theano.tensor.var.TensorVariable'> to Tensor. Contents: /dense_3_target. Consider casting elements to a supported type.

Process finished with exit code 1

**Comment by carlini** [comment]
You need to configure keras to use the tensorflow backend. It's currently set to keras.

**Comment by carlini** [comment]
They are returned as the output of the `attack` method.

**Comment by kakacharles10** [comment]
So should I add this command to the show(img) function in the test_attack.py? Thanks

**Comment by carlini** [comment]
That would work, yeah.

**Comment by kakacharles10** [comment]
Sorry for bothering again. In line 27 of test_attack.py what is the purose of "if len(img) != 784: return" How should I modify it in order to get adversarial imgaes of Cifar-10?

**Comment by carlini** [comment]
The `show` method is useful for MNIST only. You will need to write a new one for CIFAR-10.

**Comment by kakacharles10** [comment]
Is it necessary to run the train_model.py before running the test_attack.py? Since I am running out of memory

**Comment by carlini** [comment]
If you don't train the model ahead of time, it doesn't make that much sense to attack it, unless you're trying to investigate some kind of robustness property of the architecture itself using randomly initialized neural networks.

**Comment by kakacharles10** [comment]
Thanks Carlini. Since my main goal is just to get some cifar10 adversarial image data that can attack some other pre-trained neural network (like Resnet).
